version: "3.9"
name: habbo
networks:
  habbo:
    ipam:
      config:
        - subnet: 172.18.31.0/24
  traefik:
    external: true
    name: traefik
services:
  habbo_adminer:
    container_name: "habbo_adminer"
    hostname: "adminer.example.com"
    image: "adminer:latest"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.habbo_adminer.entrypoints=websecure"
      - "traefik.http.routers.habbo_adminer.rule=Host(`adminer.example.com`)"
      - "traefik.http.routers.habbo_adminer.tls.certresolver=letsencrypt"
      - "traefik.http.services.habbo_adminer.loadbalancer.server.port=8080"
    networks:
      habbo:
        ipv4_address: 172.18.31.10
      traefik: null
    restart: unless-stopped
  habbo_db:
    command:
      - '--innodb-file-per-table=1'
      - '--lower-case-table-names=0'
      - '--character-set-server=utf8mb4'
      - '--collation-server=utf8mb4_unicode_ci'
    container_name: "habbo_db"
    environment:
      - "TZ=Pacific/Auckland"
      - "MYSQL_ALLOW_EMPTY_PASSWORD=yes"
      - "MYSQL_DATABASE=havana"
      - "MYSQL_USER=havana"
      - "MYSQL_PASSWORD=${MYSQL_PASSWORD}"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    image: "mariadb:latest"
    networks:
      habbo:
        ipv4_address: 172.18.31.20
    restart: unless-stopped
    volumes:
      - "/opt/docker/habbo/db:/var/lib/mysql"
  habbo_havana:
    build: havana
    container_name: "habbo_havana"
    depends_on:
      habbo_db:
        condition: service_healthy
#    healthcheck:
#      test: ["CMD", "mysql", "-h habbo_db", "-u havana", "-pverysecret", "-e \"SHOW TABLES LIKE 'wordfilter'\"", "havana"]
#      interval: 10s
#      timeout: 5s
#      retries: 10
    hostname: "habbo_havana.example.com"
    networks:
      habbo:
        ipv4_address: 172.18.31.30
    ports:
      - "10.1.1.200:12309:12309/tcp"
      - "10.1.1.200:12321:12321/tcp"
      - "10.1.1.200:12322:12322/tcp"
    restart: unless-stopped
  habbo_minerva:
    build: minerva
    container_name: "habbo_minerva"
    hostname: "habbo_minerva.example.com"
    networks:
      habbo:
        ipv4_address: 172.18.31.40
    restart: unless-stopped
  habbo_nginx:
    build: nginx
    container_name: "habbo_nginx"
    hostname: "habbo.example.com"
    labels:
      - "traefik.docker.network=traefik"
      - "traefik.enable=true"
      - "traefik.http.routers.habbo_web.entrypoints=websecure"
      - "traefik.http.routers.habbo_web.rule=Host(`habbo.example.com`)"
      - "traefik.http.routers.habbo_web.tls.certresolver=letsencrypt"
      - "traefik.http.services.habbo_web.loadbalancer.server.port=80"
    networks:
      habbo:
        ipv4_address: 172.18.31.50
      traefik: null
    restart: unless-stopped
  habbo_web:
    build: web
    container_name: "habbo_web"
#    depends_on:
#      habbo_havana:
#        condition: service_healthy
    hostname: "habbo_web.example.com"
    networks:
      habbo:
        ipv4_address: 172.18.31.60
    restart: unless-stopped
